apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: perfectshot-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: perfectshot-web
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90
